# as per http://badsyntax.co/post/travis-ci-and-bower
language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g bower
  - bower install
after_script: istanbul cover --hook-run-in-context node_modules/mocha/bin/_mocha -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage